In [ ]:
import numpy as np
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print(a)
# Create a 2x2 array of all ones
b = np.ones((2,2))
print(b)
# Create a 3x3 constant array

c = np.full((3,3), 7)
print(c)
# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print(d)
# Create a 3x3 identity matrix
e = np.eye(3)
print(e)
# convert list to array
f = np.array([2, 3, 1, 0])
print(f)
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)
# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)
# create an array of range with float data type
i = np.arange(1, 8, dtype=float)
print(i)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.45177134 0.32132353 0.80393065]
 [0.06629421 0.39573722 0.57904962]
 [0.03729224 0.81711745 0.09209697]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]


In [ ]:
import numpy as np

x = np.array([0, 1])
y = np.array([2.0, 3.0])
z = np.array([5, 6], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)


int64 float64 int64


In [ ]:
import numpy as np
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:
import numpy as np
a = np.array([1, 2, 5, 3])
# add 1 to every element
print ("Adding 1 to every element:", a+1)
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
# square each element
print ("Squaring each element:", a**2)
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [17]:
import pdfplumber

with pdfplumber.open('/content/3 (1).pdf') as pdf:
first_page = pdf.pages[0]
text = first_page.extract_text()
print(text)

IndentationError: expected an indented block after 'with' statement on line 3 (ipython-input-3904331077.py, line 4)

In [ ]:
import numpy as np
arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))
# sum of array elements
print ("Sum of all array elements:",arr.sum())
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
import numpy as np
a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])
# add arrays
print ("Array sum:\n", a + b)
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
import numpy as np
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [ ]:
import pandas as pd
import io

csv_data = """date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg
06-10-2017,5464,200,181,5,0,66
07-10-2017,6041,100,197,8,0,66
08-10-2017,25,100,0,5,0,66
09-10-2017,5461,100,174,4,0,66
10-10-2017,6915,200,223,5,500,66
11-10-2017,4545,100,149,6,0,66
12-10-2017,4340,100,140,6,0,66
13-10-2017,1230,100,38,7,0,66
14-10-2017,61,100,1,5,0,66
15-10-2017,1258,100,40,6,0,65
16-10-2017,3148,100,101,8,0,65
17-10-2017,4687,100,152,5,0,65
18-10-2017,4732,300,150,6,500,65
19-10-2017,3519,100,113,7,0,65
20-10-2017,1580,100,49,5,0,65
21-10-2017,2822,100,86,6,0,65
22-10-2017,181,100,6,8,0,65
23-10-2017,3158,200,99,5,0,65
24-10-2017,4383,200,143,4,0,64
25-10-2017,3881,200,125,5,0,64
26-10-2017,4037,200,129,6,0,64
27-10-2017,202,200,6,8,0,64
28-10-2017,292,200,9,5,0,64
29-10-2017,330,300,10,6,0,64
30-10-2017,2209,200,72,5,0,64
31-10-2017,4550,300,150,8,500,64
01-11-2017,4435,300,141,5,0,64
02-11-2017,4779,300,156,4,0,64
03-11-2017,1831,300,57,5,0,64
04-11-2017,2255,300,72,4,0,64
05-11-2017,539,300,17,5,500,64
06-11-2017,5464,300,181,4,0,64
07-11-2017,6041,200,197,3,0,64
08-11-2017,4068,300,131,2,0,64
09-11-2017,4683,300,154,9,0,64
10-11-2017,4033,300,137,5,0,64
11-11-2017,6314,300,193,6,500,64
12-11-2017,614,300,19,4,500,64
13-11-2017,3149,300,101,5,500,64
14-11-2017,4005,300,139,8,500,64
15-11-2017,4880,300,164,4,500,64
16-11-2017,4136,300,137,5,500,64
17-11-2017,705,300,22,6,500,64
18-11-2017,570,200,17,5,500,64
19-11-2017,269,300,9,6,500,64
20-11-2017,4275,300,145,5,0,64
21-11-2017,5999,300,192,6,0,64
22-11-2017,4421,300,146,5,0,64
23-11-2017,6930,300,234,6,0,64
24-11-2017,5195,300,167,5,0,64
25-11-2017,546,300,16,6,0,64
26-11-2017,493,300,17,7,500,64
27-11-2017,995,300,32,6,500,64
28-11-2017,1163,200,35,7,500,64
29-11-2017,6676,100,220,6,500,64
30-11-2017,3608,300,116,5,500,64
01-12-2017,774,300,23,6,500,64
02-12-2017,1421,300,44,7,500,64
03-12-2017,4064,300,131,8,500,64
04-12-2017,2725,300,86,8,500,64
05-12-2017,5934,300,194,7,500,64
06-12-2017,1867,300,60,8,500,64
07-12-2017,3721,100,121,5,500,64
08-12-2017,2374,200,76,4,0,64
09-12-2017,2909,200,93,3,500,64
10-12-2017,1648,100,53,3,500,64
11-12-2017,799,100,25,4,0,64
12-12-2017,7102,200,227,5,500,64
13-12-2017,3941,200,125,5,500,64
14-12-2017,7422,300,243,5,500,64
15-12-2017,437,200,14,3,500,64
16-12-2017,1231,200,39,4,500,64
17-12-2017,1696,100,55,4,0,64
18-12-2017,4921,200,158,5,500,64
19-12-2017,221,100,7,5,500,64
20-12-2017,6500,200,213,5,500,64
21-12-2017,3575,200,116,5,500,64
22-12-2017,4061,100,129,5,0,64
23-12-2017,651,100,21,5,0,64
24-12-2017,753,100,28,4,0,64
25-12-2017,518,100,16,3,0,64
26-12-2017,5537,300,180,4,500,64
27-12-2017,4108,200,138,5,500,64
28-12-2017,5376,300,176,5,500,64
29-12-2017,3066,200,99,4,500,64
30-12-2017,177,100,5,5,0,64
31-12-2017,36,100,1,3,0,64
01-01-2018,299,100,10,3,0,64
02-01-2018,1447,200,47,3,0,64
03-01-2018,2599,200,84,2,0,64
04-01-2018,702,100,23,3,0,64
05-01-2018,133,100,4,2,0,64
06-01-2018,153,300,0,8,0,64
07-01-2018,500,200,0,5,500,64
08-01-2018,2127,200,0,5,0,64
09-01-2018,2203,300,0,5,500,64
"""

df = pd.read_csv(io.StringIO(csv_data))
display(df.head())

date  step_count  mood  calories_burned  hours_of_sleep  \
0  06-10-2017        5464   200              181               5   
1  07-10-2017        6041   100              197               8   
2  08-10-2017          25   100                0               5   
3  09-10-2017        5461   100              174               4   
4  10-10-2017        6915   200              223               5   

   bool_of_active  weight_kg  
0               0         66  
1               0         66  
2               0         66  
3               0         66  
4             500         66

from matplotlib import pyplot as plt
_df_0['step_count'].plot(kind='hist', bins=20, title='step_count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['mood'].plot(kind='hist', bins=20, title='mood')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['calories_burned'].plot(kind='hist', bins=20, title='calories_burned')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['hours_of_sleep'].plot(kind='hist', bins=20, title='hours_of_sleep')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('date').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='step_count', y='mood', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='mood', y='calories_burned', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='calories_burned', y='hours_of_sleep', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='hours_of_sleep', y='bool_of_active', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['step_count']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('date')):
  _plot_series(series, series_name, i)
  fig.legend(title='date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('step_count')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['mood']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('date')):
  _plot_series(series, series_name, i)
  fig.legend(title='date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('mood')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['calories_burned']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('date')):
  _plot_series(series, series_name, i)
  fig.legend(title='date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('calories_burned')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['hours_of_sleep']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('date')):
  _plot_series(series, series_name, i)
  fig.legend(title='date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('hours_of_sleep')

from matplotlib import pyplot as plt
_df_13['step_count'].plot(kind='line', figsize=(8, 4), title='step_count')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['mood'].plot(kind='line', figsize=(8, 4), title='mood')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['calories_burned'].plot(kind='line', figsize=(8, 4), title='calories_burned')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['hours_of_sleep'].plot(kind='line', figsize=(8, 4), title='hours_of_sleep')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='step_count', y='date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='mood', y='date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='calories_burned', y='date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='hours_of_sleep', y='date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)